"""logs e etc...

Revision ID: 057b1a79849b
Revises: 5933f742c0e5
Create Date: 2025-09-03 18:59:31.177865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057b1a79849b'
down_revision = '5933f742c0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=False))
        batch_op.alter_column('login_nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint('uq_user_login_nome', ['login_nome'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_login_nome', type_='unique')
        batch_op.alter_column('login_nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
