"""inclusao da descricao no bd Protudo

Revision ID: 5933f742c0e5
Revises: 5d5fdaf08480
Create Date: 2025-09-03 17:07:00.721485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5933f742c0e5'
down_revision = '5d5fdaf08480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
