"""Adiciona campo ativo ao usuário

Revision ID: de42889d85d2
Revises: 057b1a79849b
Create Date: 2025-09-06 07:54:09.142853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de42889d85d2'
down_revision = '057b1a79849b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=False, server_default=sa.text('1')))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
